/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#958da1',
        'on-secondary': '#003640',
        'inverse-surface': '#dfe2f1',
        'on-tertiary-fixed': '#231b00',
        'primary-container': '#7c3aed',
        'primary-fixed': '#eaddff',
        'error-container': '#93000a',
        'tertiary-container': '#cea700',
        surface: '#0f131d',
        primary: '#d2bbff',
        'on-primary': '#3f008e',
        'secondary-fixed-dim': '#4cd7f6',
        'on-secondary-container': '#00424e',
        'surface-tint': '#d2bbff',
        'on-primary-fixed': '#25005a',
        'on-tertiary': '#3c2f00',
        'secondary-fixed': '#acedff',
        secondary: '#4cd7f6',
        'surface-container': '#1c1f2a',
        'tertiary-fixed': '#ffe083',
        'on-secondary-fixed-variant': '#004e5c',
        'inverse-on-surface': '#2c303b',
        'on-tertiary-fixed-variant': '#574500',
        error: '#ffb4ab',
        'surface-container-low': '#171b26',
        background: '#0f131d',
        'on-surface-variant': '#ccc3d8',
        'tertiary-fixed-dim': '#eec200',
        'secondary-container': '#03b5d3',
        'surface-container-lowest': '#0a0e18',
        tertiary: '#efc200',
        'on-background': '#dfe2f1',
        'surface-dim': '#0f131d',
        'on-tertiary-container': '#4e3e00',
        'on-primary-container': '#ede0ff',
        'inverse-primary': '#732ee4',
        'surface-container-highest': '#313540',
        'on-error': '#690005',
        'surface-variant': '#313540',
        'surface-container-high': '#262a35',
        'primary-fixed-dim': '#d2bbff',
        'on-primary-fixed-variant': '#5a00c6',
        'on-surface': '#dfe2f1',
        'on-error-container': '#ffdad6',
        'surface-bright': '#353944',
        'on-secondary-fixed': '#001f26',
        'outline-variant': '#4a4455',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-lg': '1.5rem',
        'space-md': '1rem',
        'container-max': '72rem',
        'gutter-sm': '1rem',
        'space-xs': '0.5rem',
        'space-xl': '2rem',
        'space-3xl': '4.5rem',
        'gutter-lg': '2rem',
        'space-sm': '0.75rem',
        'space-2xl': '3rem',
        'gutter-md': '1.5rem',
      },
      fontFamily: {
        'body-md': ['Be Vietnam Pro', 'sans-serif'],
        'headline-sm': ['Outfit', 'sans-serif'],
        'display-hero-mobile': ['Fredoka', 'sans-serif'],
        'headline-lg': ['Outfit', 'sans-serif'],
        'headline-md': ['Outfit', 'sans-serif'],
        'title-badge': ['Outfit', 'sans-serif'],
        'headline-lg-mobile': ['Outfit', 'sans-serif'],
        'display-hero': ['Fredoka', 'sans-serif'],
        'body-lg': ['Be Vietnam Pro', 'sans-serif'],
        'label-mission': ['Outfit', 'sans-serif'],
        'body-sm': ['Be Vietnam Pro', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'display-hero-mobile': [
          '64px',
          { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'title-badge': ['15px', { lineHeight: '20px', letterSpacing: '0.06em', fontWeight: '800' }],
        'headline-lg-mobile': [
          '28px',
          { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '800' },
        ],
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '900' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-mission': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
